[package]
name = "sxg_rs"
version = "0.1.0"
authors = ["9083193+antiphoton@users.noreply.github.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
der-parser = { version = "5.1.0", features = ["bigint", "serialize"] }
futures = { version = "0.3.14", features = ["executor"] }
js-sys = "0.3.50"
nom = { version = "6.1.2", features = ["alloc"] }
once_cell = "1.7.2"
sha2 = "0.9.3"
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.23"
x509-parser = "0.9.2"

[dependencies.p256]
version = "0.7.2"
features = ["ecdsa"]
