[package]
name = "sxg_rs"
version = "0.1.0"
authors = ["9083193+antiphoton@users.noreply.github.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
once_cell = "1.7.2"
sha2 = "0.9.3"

[dependencies.p256]
version = "0.7.2"
features = ["ecdsa"]
